services:

    # Not found listener
    web.listener:
        class: Vizzle\WebBundle\Listener\NotFoundListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 2048 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }